CREATE DATABASE hello;
USE hello;
CREATE TABLE USER (
name VARCHAR (20) PRIMARY KEY NOT NULL ,
password VARCHAR (20) NOT NULL ,
gender VARCHAR (10) NOT NULL ,
avatar VARCHAR (10) NOT NULL ,
phone VARCHAR (11) NOT NULL ,
email VARCHAR (30) NOT NULL
);

